#!/usr/bin/env python3

# authored by Sahejveer, Tristan, Ali & Kyler

import os
import sys
import json

INPUT_FILE = 'data/output.json'

def usage():
	print('Usage: coursesearch <course_code> [--in input_file.json]')

# python3 coursesearch.py [args..]
# coursesearch CIS*3760
# coursesearch --help

if len(sys.argv) != 2:
	if len(sys.argv) == 4 and sys.argv[2] == '--in':
		INPUT_FILE = sys.argv[3]
	else:
		usage()
		sys.exit()

if sys.argv[1] == '-h' or sys.argv[1] == '--help':
	usage()
	sys.exit()

# check for existence of input file
if not os.path.exists(INPUT_FILE):
    print('coursesearch: input file does not exist')
    sys.exit()

# assign searched value to a variable
search_course = sys.argv[1]

file = open(INPUT_FILE)
courseData = json.load(file) # load json data in dictionary

# if courseData contains sys.argv[1] then print info else course does not exist

if search_course in courseData:
    course = courseData[search_course]
    
    print("\nCourse: ", search_course)
    print("\nName:", course.get('name'))
    print("\nTerm:", course.get('term'))
    print("\nStaus:", course.get('status'))
    print("\nLocation:", course.get('location'))
    print("\nMeetingInfo:", course.get('meetingInfo'))
    print("\nCapacity:", course.get('capacity'))
    print("\nCredit:", course.get('credit'))
    print("\nAcademic Level:", course.get('academiclevel'))
    print("\n")
else:
	print("Course does not exist")
