#!/usr/bin/env python3

import os
import sys
import json

INPUT_DATA = 'data/output.json'

def usage():
	print('Usage: coursesearch <course_code> [--in input_file.json]')

# python3 coursesearch.py [args..]
# coursesearch CIS*3760
# coursesearch --help

if len(sys.argv) != 2:
	if len(sys.argv) == 4 and sys.argv[2] == '--in':
		INPUT_DATA = sys.argv[3]
	else:
		usage()
		sys.exit()

if sys.argv[1] == '-h' or sys.argv[1] == '--help':
	usage()
	sys.exit()

search_course = sys.argv[1]

file = open('jsonFile.json')
courseData = json.load(file)