version: '3.9'
services:
  app:
    container_name: app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./client/nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./client/nginx/localhost.crt:/etc/nginx/localhost.crt
      - ./client/nginx/localhost.key:/etc/nginx/localhost.key
  api:
    container_name: api
    build: ./server
    environment:
      - API_PREFIX=/api
    ports:
      - '3001:3001'
    command: ['flask', '--debug', 'run', '--host', '0.0.0.0', '--port', '3001']
