version: '3.9'
services:
  app:
    container_name: app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '443:443'
    volumes:
      - ./client:/src
      - /src/node_modules
  api:
    container_name: api
    build: ./server
    environment:
      - API_PREFIX=/api
    ports:
      - '3001:3001'
    volumes:
      - ./server:/src
    command: ['flask', '--debug', 'run', '--host', '0.0.0.0', '--port', '3001']
