version: '3.9'
services:
  app:
    container_name: app
    build: ./client
    ports:
      - '443:443'
    volumes:
      - ./client/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/nginx/localhost.crt:/etc/nginx/localhost.crt
      - ./client/nginx/localhost.key:/etc/nginx/localhost.key
  api:
    container_name: api
    build: ./server
    ports:
      - '5000:5000'
