version: '3.9'
services:
  app:
    container_name: app
    build:
      context: ./client
      target: 'base'
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    command: ['npm', 'start']
  api:
    container_name: api
    build: ./server
    environment:
      - FLASK_ENV=development
    ports:
      - '3001:3001'
    volumes:
      - ./server:/src
    command: ['flask', '--app', 'app', '--debug', 'run', '--host', '0.0.0.0', '--port', '3001']
  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - app
      - api
    environment:
      - CYPRESS_baseUrl=http://app:3000
      - CYPRESS_VIDEO=true
    command: npx wait-on http://app:3000 && npx cypress run --browser chrome
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.config.js:/app/cypress.config.js
