version: '3.9'
services:
  app:
    container_name: app
    build: ./client
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./client/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/nginx/localhost.crt:/etc/nginx/localhost.crt
      - ./client/nginx/localhost.key:/etc/nginx/localhost.key
  api:
    container_name: api
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
    command: ['python3', '-m', 'flask', 'run', '--host=0.0.0.0', '--port=5000']
