#!/usr/bin/python3

import sys
import json
from src.htmlparser.core import HTMLCourseParser

def usage():
	print('Usage: htmlparser <html_file>')

if len(sys.argv) != 2:
    usage()
    sys.exit()

file = sys.argv[1]

# count is only used for debugging, if the parser fails at a line in the HTMl this will tell us which line if we print it
# could be used to implement easy debug mode in the future
count = 0

parser = HTMLCourseParser()

try:
    with open(file, 'r') as f:
        for line in f:
            count += 1
            parser.feed(line)
            parser.close()
except IOError:
    print("File not found.")


with open('data/results.json', 'w') as f:
    json.dump(parser.get_course_dict(), f, indent=4)

with open('data/course_mapping.json', 'w') as f:
    json.dump(parser.get_course_mapping(), f, indent=4)



