#!/usr/bin/python3

import sys

from src.jsontocsv.core import JSONToCSV


INPUT_FILE = 'data/results.json'
OUTPUT_DIR = 'csv'

if len(sys.argv) == 2:
    if sys.argv[1] == '-h' or sys.argv[1] == '--help':
        print('Usage: ./json-to-csv [input_json] [output_dir]')
        sys.exit()
    else:
        INPUT_FILE = sys.argv[1]

if len(sys.argv) == 3:
    INPUT_FILE = sys.argv[1]
    OUTPUT_DIR = sys.argv[2]

if len(sys.argv) > 3:
    print('Usage: ./json-to-csv [input_json] [output_dir]')
    sys.exit()

jsontocsv = JSONToCSV(INPUT_FILE)

jsontocsv.createSectionsCSV(OUTPUT_DIR + '/sections.csv')
jsontocsv.createMeetingsCSV(OUTPUT_DIR + '/meetings.csv')