name: Lint + Test

on:
  pull_request:
    branches:
      - sprint*

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ESLint (frontend)
        run: |-
          cd client
          npm install
          npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run PyLint (backend)
        run: |-
          cd server
          pip install -r requirements.txt
          pylint *.py --rcfile pylintrc

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start services and test
        run: |-
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from e2e

      - name: Upload failure images
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots

      - name: Upload result videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos
