name: Linting

on:
  push:
    branches:
      - feature/**

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ESLint
        run: |-
          cd client
          npm install
          npx eslint . --ext .js,.jsx,.ts,.tsx
