name: Testing

on:
  pull_request:
    branches:
      - sprint*

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Docker containers
        run: |-
          docker-compose -f docker-compose.test.yml up --build --detach

      - name: Run cypress e2e tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: client
          wait-on: 'http://localhost:3000/'

      - name: Upload failure images
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots

      - name: Upload result videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: client/cypress/videos
