name: Testing

on:
  pull_request:
    branches:
      - sprint*

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start services and test
        run: |-
          docker-compose build -f docker-compose.test.yml
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from e2e

      - name: Upload failure images
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: app/cypress/screenshots

      - name: Upload result videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: app/cypress/videos
